import { StyleSheet } from 'react-native';

module.exports = StyleSheet.create({
  buttonInput: {
    width: '100%',
    borderWidth: 2,
    borderRadius: 10,
    padding: '5%',
    margin: '0%',
    marginTop: '1%',
    marginBottom: '1%',
    backgroundColor: 'rgba(20, 20, 255, 0.85)',
    borderColor: 'rgba(253, 60, 28, 1)',
  },
  buttonInputApprovalPending: {
    width: '100%',
    borderWidth: 2,
    borderRadius: 10,
    padding: '5%',
    margin: '0%',
    marginTop: '1%',
    marginBottom: '1%',
    backgroundColor: 'rgba(1, 1, 1, 0.85)',
    borderColor: 'rgba(253, 60, 28, 1)',
  },
  buttonText: {
    textAlign: 'center',
    fontWeight: 'bold',
    color: 'white',
    fontSize: 15,
  },
  menuInput: {
    borderWidth: 2,
    borderRadius: 10,
    paddingLeft: '3%',
    paddingRight: '3%',
    marginRight: '2%',
    backgroundColor: 'rgba(20, 20, 255, 0.65)',
    borderColor: 'rgba(253, 60, 28, 1)',
  },
  logoutInput: {
    borderWidth: 2,
    borderRadius: 10,
    paddingLeft: '3%',
    paddingRight: '3%',
    marginRight: '2%',
    backgroundColor: 'rgba(255, 0, 0, 0.65)',
    borderColor: 'rgba(253, 60, 28, 1)',
  },
});
